spring:
  datasource:
    url: jdbc:mysql://kem.greenkoncepts.com:32224/GKTECHNICALTEST
    driverClassName: com.mysql.jdbc.Driver
    username: gktest
    password: gktest123
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect